import { OperationConfig } from './types'

export const FIELD_LABELS: Record<string, string> = {
  // Machine Details
  machine_name: 'Machine Name',
  machine_number: 'Machine Number',
  machine_type: 'Machine Type',
  coolant_type: 'Coolant Type',
  rpm_range: 'RPM Range',
  power_rating: 'Power Rating (kW)',
  
  // Job Details
  part_name: 'Part Name',
  part_number: 'Part Number',
  material: 'Material',
  hardness: 'Hardness (HRC)',
  module: 'Module (mm)',
  no_of_teeth: 'Number of Teeth',
  helix_angle: 'Helix Angle',
  pressure_angle: 'Pressure Angle',
  face_width: 'Face Width (mm)',
  tip_diameter: 'Tip Diameter (mm)',
  root_diameter: 'Root Diameter (mm)',
  bore_diameter: 'Bore Diameter (mm)',
  grinding_allowance: 'Grinding Allowance (mm)',
  
  // Cutting Parameters
  cutting_speed: 'Cutting Speed (m/min)',
  feed_rate: 'Feed Rate (mm/rev)',
  depth_of_cut: 'Depth of Cut (mm)',
  rpm: 'RPM',
  infeed: 'Infeed (mm)',
  dressing_frequency: 'Dressing Frequency',
  spark_out_passes: 'Spark Out Passes',
  wheel_speed: 'Wheel Speed (m/s)',
  work_speed: 'Work Speed (RPM)',
  traverse_rate: 'Traverse Rate (mm/min)',
  plunge_rate: 'Plunge Rate (mm/min)',
  
  // Tool Details
  tool_type: 'Tool Type',
  tool_material: 'Tool Material',
  tool_diameter: 'Tool Diameter (mm)',
  tool_length: 'Tool Length (mm)',
  no_of_flutes: 'Number of Flutes',
  hob_type: 'Hob Type',
  hob_diameter: 'Hob Diameter (mm)',
  hob_length: 'Hob Length (mm)',
  no_of_starts: 'Number of Starts',
  wheel_type: 'Wheel Type',
  wheel_diameter: 'Wheel Diameter (mm)',
  wheel_width: 'Wheel Width (mm)',
  grit_size: 'Grit Size',
  bond_type: 'Bond Type',
  abrasive_type: 'Abrasive Type',
  cutter_type: 'Cutter Type',
  cutter_diameter: 'Cutter Diameter (mm)',
  no_of_teeth_cutter: 'Number of Teeth (Cutter)',
}

export const OPERATIONS: OperationConfig[] = [
  {
    type: 'hobbing',
    label: 'Hobbing',
    icon: '⚙️',
    color: 'bg-blue-500',
    machineFields: ['machine_name', 'machine_number', 'coolant_type', 'rpm_range', 'power_rating'],
    jobFields: ['part_name', 'part_number', 'material', 'module', 'no_of_teeth', 'helix_angle', 'pressure_angle', 'face_width', 'tip_diameter'],
    cuttingFields: ['cutting_speed', 'feed_rate', 'depth_of_cut', 'rpm'],
    toolFields: ['hob_type', 'hob_diameter', 'hob_length', 'no_of_starts', 'tool_material'],
  },
  {
    type: 'shaping',
    label: 'Shaping',
    icon: '🔧',
    color: 'bg-emerald-500',
    machineFields: ['machine_name', 'machine_number', 'coolant_type', 'power_rating'],
    jobFields: ['part_name', 'part_number', 'material', 'module', 'no_of_teeth', 'helix_angle', 'pressure_angle', 'face_width'],
    cuttingFields: ['cutting_speed', 'feed_rate', 'depth_of_cut', 'rpm'],
    toolFields: ['cutter_type', 'cutter_diameter', 'no_of_teeth_cutter', 'tool_material'],
  },
  {
    type: 'shaving',
    label: 'Shaving',
    icon: '✂️',
    color: 'bg-amber-500',
    machineFields: ['machine_name', 'machine_number', 'coolant_type'],
    jobFields: ['part_name', 'part_number', 'material', 'module', 'no_of_teeth', 'face_width'],
    cuttingFields: ['cutting_speed', 'feed_rate', 'infeed', 'rpm'],
    toolFields: ['cutter_type', 'cutter_diameter', 'tool_material'],
  },
  {
    type: 'hard-turning',
    label: 'Hard Turning',
    icon: '🔩',
    color: 'bg-red-500',
    machineFields: ['machine_name', 'machine_number', 'coolant_type', 'power_rating'],
    jobFields: ['part_name', 'part_number', 'material', 'hardness', 'bore_diameter', 'face_width'],
    cuttingFields: ['cutting_speed', 'feed_rate', 'depth_of_cut', 'rpm'],
    toolFields: ['tool_type', 'tool_material', 'tool_diameter', 'tool_length'],
  },
  {
    type: 'od-grinding',
    label: 'OD Grinding',
    icon: '🎯',
    color: 'bg-purple-500',
    machineFields: ['machine_name', 'machine_number', 'coolant_type', 'power_rating'],
    jobFields: ['part_name', 'part_number', 'material', 'hardness', 'tip_diameter', 'face_width', 'grinding_allowance'],
    cuttingFields: ['wheel_speed', 'work_speed', 'infeed', 'traverse_rate', 'dressing_frequency', 'spark_out_passes'],
    toolFields: ['wheel_type', 'wheel_diameter', 'wheel_width', 'grit_size', 'bond_type', 'abrasive_type'],
  },
  {
    type: 'id-grinding',
    label: 'ID Grinding',
    icon: '⭕',
    color: 'bg-cyan-500',
    machineFields: ['machine_name', 'machine_number', 'coolant_type', 'power_rating'],
    jobFields: ['part_name', 'part_number', 'material', 'hardness', 'bore_diameter', 'face_width', 'grinding_allowance'],
    cuttingFields: ['wheel_speed', 'work_speed', 'infeed', 'plunge_rate', 'dressing_frequency', 'spark_out_passes'],
    toolFields: ['wheel_type', 'wheel_diameter', 'wheel_width', 'grit_size', 'bond_type', 'abrasive_type'],
  },
  {
    type: 'gear-grinding',
    label: 'Gear Grinding',
    icon: '⚡',
    color: 'bg-orange-500',
    machineFields: ['machine_name', 'machine_number', 'coolant_type', 'power_rating'],
    jobFields: ['part_name', 'part_number', 'material', 'hardness', 'module', 'no_of_teeth', 'helix_angle', 'pressure_angle', 'face_width', 'grinding_allowance'],
    cuttingFields: ['wheel_speed', 'work_speed', 'infeed', 'dressing_frequency', 'spark_out_passes'],
    toolFields: ['wheel_type', 'wheel_diameter', 'wheel_width', 'grit_size', 'bond_type', 'abrasive_type'],
  },
]

export function getOperationConfig(type: string): OperationConfig | undefined {
  return OPERATIONS.find(op => op.type === type)
}
